### ISSUE TITLE
Save harpoiner menu on each edit

### ISSUE THREAD

**Issue by Parker7123** [erotourtes/Harpooner#5]
Great idea with this interactive file acting as a list.
Is it possible to save menu file on each edit?
Now when I edit the list I am forced to close the tab to apply changes which obviously isn't ideal.

**Comment by erotourtes** [comment]
Hey! Unfortunately, it is not possible, and I am a bit busy right now, so I won't work on the project for at least a week.

For now, all I can suggest is if you're using the IdeaVim plugin you can close an editor (tab) by just pressing ":q"   ;p
