### ISSUE TITLE
Files deleted from list are still accessible

### ISSUE THREAD

**Issue by Parker7123** [erotourtes/Harpooner#6]
Something seems not to work properly. After I delete content form Harpooner list it is cached somewhere and not deleted.
Steps to reproduce:

1. Add files to list
2. Open Harpooner Menu file and delete it's content
3. Save the file :w
4. Close the tab
5. Try to access any file from the list for example with HarpoonerOpenFile0
6. File is opened despite Harpooner list being empty
7. Open Harpooner Menu file again
8. It has all it's content despite being deleted in step 2

**Comment by erotourtes** [comment]
Hey, I didn't face that problem when using IntelliJ Ultimate. I guess the issue stems from API variations across different products. Could you specify which one you're using?

**Comment by Parker7123** [comment]
IntelijJ Ultimate 2023.3.3. I'm not sure whether this is the root cause, but having two files Harpooner Menu and Harpooner.xml content between these two is not syncrhonized for some reason. Files removed from Harpooner Menu are visible under Harpooner.xml.

**Comment by erotourtes** [comment]
Thanks, I optimized the behavior. Let me know if you encounter further issues
